name: "Verify, build and create artifacts"

on:
  release:
    types: [prereleased, published]

env:
  NODE: 12.20.1
  METEOR: 2.0

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: env.NODE
      - run: npm ci
      - run: npm run lint
  test-meteor:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: env.METEOR
      - run: meteor npm install
      - run: npm run test
  deploy:
    runs-on: ubuntu-20.04
    needs: [lint, test-meteor]
    steps:
      - uses: actions/checkout@v1
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: env.METEOR
      - name: Install dependencies
        run: meteor npm install
      - name: Build application
        run: npm run build
      - name: Upload application bundle
        uses: actions/upload-artifact@v2
        with:
          name: meteor-ip-cam-recorder.tar.gz
          path: meteor-ip-cam-recorder.tar.gz
