name: release

on:
  release:
    types: [published]

env:
  NODE: '12.20.1'
  METEOR: '2.0'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}
      - run: npm ci
      - run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v1

      - name: Setup Meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ env.METEOR }}

      - name: Install dependencies
        run: meteor npm install

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build

      - name: Upload application bundle to the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app.tar.gz
          path: meteor-ip-cam-recorder.tar.gz

      - name: Retrieve UPLOAD_URL
        id: get_release
        run: |
          upload_url=$(curl -sL https://api.github.com/repos/boonya/meteor-ip-cam-recorder/releases/tags/${{ github.ref }} | jq -r '.upload_url')
          ::set-output name=UPLOAD_URL::$upload_url
          echo "::debug::UPLOAD_URL"
        shell: bash

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          # asset_path: meteor-ip-cam-recorder.tar.gz
          # asset_name: app.tar.gz
          # asset_content_type: application/gzip
