name: Lint and test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENCE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENCE'

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.20.1
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: 2.0
      - run: meteor npm install
      - run: npm run test
