name: verification

on:
  push:
    branch-ignore:
      - build-docker-image
    paths-ignore:
      - '**.md'
      - 'LICENCE'
  pull_request:
    branch-ignore:
      - build-docker-image
    paths-ignore:
      - '**.md'
      - 'LICENCE'

env:
  NODE: '12.20.1'
  METEOR: '2.0'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}
      - run: npm ci
      - run: npm run lint
  test-meteor:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ env.METEOR }}
      - run: meteor npm install
      - run: npm run test
